---
name: docker-builder-latest

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

on:
  push:
    branches:
      - 'master'
      - '**'
  repository_dispatch:
    types:
      - refresh

jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout ✅
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup QEMU for multi-arch builds 🏗️
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/arm64/v8,linux/amd64"

      - name: Setup Docker buildX for multi-arch builds 🏗️
        uses: docker/setup-buildx-action@v3

      - name: Login to the container registry 🗝️
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for TAG
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_IMAGE }}
          tags: |
            type=match,pattern=(v.*),group=1

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          context: docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8,linux/amd64
